export const GAME_SYMBOLS = {
  CROSS: "CROSS",
  NOUGHT: "NOUGHT",
  TRIANGLE: "TRIANGLE",
  SQUARE: "SQUARE",
};

export const MOVE_ORDER = [
  GAME_SYMBOLS.CROSS,
  GAME_SYMBOLS.NOUGHT,
  GAME_SYMBOLS.TRIANGLE,
  GAME_SYMBOLS.SQUARE,
];
